{"metadata":{"symbolKind":"enum","title":"PyException","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PyException","kind":"identifier"}],"navigatorTitle":[{"text":"PyException","kind":"identifier"}],"role":"symbol","roleHeading":"Enumeration","modules":[{"name":"_PythonString"}],"externalID":"s:13_PythonString11PyExceptionO"},"variants":[{"paths":["\/documentation\/_pythonstring\/pyexception"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PyException"}]}]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.swallow.documentation._PythonString\/s8CopyableP","doc:\/\/com.swallow.documentation._PythonString\/s23CustomStringConvertibleP","doc:\/\/com.swallow.documentation._PythonString\/s5ErrorP","doc:\/\/com.swallow.documentation._PythonString\/s8SendableP"],"title":"Conforms To","type":"conformsTo"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException"},"topicSections":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/attributeError(_:)","doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/baseException(_:)","doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/exception(_:)","doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/indexError(_:)","doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/keyError(_:)","doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/overflowError(_:)","doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/systemError(_:)","doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/typeError(_:)","doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/valueError(_:)"],"generated":true,"title":"Enumeration Cases"},{"generated":true,"identifiers":["doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/CustomStringConvertible-Implementations","doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/Error-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations"}],"references":{"doc://com.swallow.documentation._PythonString/documentation/_PythonString/PyException/CustomStringConvertible-Implementations":{"identifier":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/CustomStringConvertible-Implementations","abstract":[],"url":"\/documentation\/_pythonstring\/pyexception\/customstringconvertible-implementations","type":"topic","role":"collectionGroup","kind":"article","title":"CustomStringConvertible Implementations"},"doc://com.swallow.documentation._PythonString/documentation/_PythonString/PyException/indexError(_:)":{"kind":"symbol","role":"symbol","title":"PyException.indexError(_:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/indexError(_:)","type":"topic","abstract":[],"url":"\/documentation\/_pythonstring\/pyexception\/indexerror(_:)"},"doc://com.swallow.documentation._PythonString/documentation/_PythonString/PyException/baseException(_:)":{"identifier":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/baseException(_:)","title":"PyException.baseException(_:)","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"baseException","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"url":"\/documentation\/_pythonstring\/pyexception\/baseexception(_:)","type":"topic","abstract":[],"role":"symbol"},"doc://com.swallow.documentation._PythonString/documentation/_PythonString/PyException/attributeError(_:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"attributeError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"PyException.attributeError(_:)","type":"topic","abstract":[],"identifier":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/attributeError(_:)","url":"\/documentation\/_pythonstring\/pyexception\/attributeerror(_:)","role":"symbol"},"doc://com.swallow.documentation._PythonString/documentation/_PythonString/PyException/keyError(_:)":{"role":"symbol","url":"\/documentation\/_pythonstring\/pyexception\/keyerror(_:)","identifier":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/keyError(_:)","abstract":[],"type":"topic","title":"PyException.keyError(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"keyError","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.swallow.documentation._PythonString/documentation/_PythonString/PyException/Error-Implementations":{"abstract":[],"url":"\/documentation\/_pythonstring\/pyexception\/error-implementations","title":"Error Implementations","role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/Error-Implementations","kind":"article"},"doc://com.swallow.documentation._PythonString/documentation/_PythonString/PyException":{"title":"PyException","navigatorTitle":[{"text":"PyException","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/_pythonstring\/pyexception","kind":"symbol","identifier":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PyException","kind":"identifier"}]},"doc://com.swallow.documentation._PythonString/documentation/_PythonString/PyException/typeError(_:)":{"title":"PyException.typeError(_:)","url":"\/documentation\/_pythonstring\/pyexception\/typeerror(_:)","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"typeError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"abstract":[],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/typeError(_:)"},"doc://com.swallow.documentation._PythonString/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.swallow.documentation._PythonString\/s8SendableP"},"doc://com.swallow.documentation._PythonString/documentation/_PythonString/PyException/valueError(_:)":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"valueError","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/_pythonstring\/pyexception\/valueerror(_:)","identifier":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/valueError(_:)","kind":"symbol","type":"topic","title":"PyException.valueError(_:)","abstract":[],"role":"symbol"},"doc://com.swallow.documentation._PythonString/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.swallow.documentation._PythonString\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.swallow.documentation._PythonString/documentation/_PythonString/PyException/overflowError(_:)":{"identifier":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/overflowError(_:)","kind":"symbol","url":"\/documentation\/_pythonstring\/pyexception\/overflowerror(_:)","title":"PyException.overflowError(_:)","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"overflowError","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[],"role":"symbol"},"doc://com.swallow.documentation._PythonString/documentation/_PythonString/PyException/systemError(_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"systemError"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/systemError(_:)","title":"PyException.systemError(_:)","abstract":[],"url":"\/documentation\/_pythonstring\/pyexception\/systemerror(_:)","kind":"symbol","type":"topic"},"doc://com.swallow.documentation._PythonString/s8CopyableP":{"identifier":"doc:\/\/com.swallow.documentation._PythonString\/s8CopyableP","title":"Swift.Copyable","type":"unresolvable"},"doc://com.swallow.documentation._PythonString/s5ErrorP":{"identifier":"doc:\/\/com.swallow.documentation._PythonString\/s5ErrorP","title":"Swift.Error","type":"unresolvable"},"doc://com.swallow.documentation._PythonString/documentation/_PythonString":{"abstract":[],"role":"collection","title":"_PythonString","identifier":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString","url":"\/documentation\/_pythonstring","type":"topic","kind":"symbol"},"doc://com.swallow.documentation._PythonString/documentation/_PythonString/PyException/exception(_:)":{"identifier":"doc:\/\/com.swallow.documentation._PythonString\/documentation\/_PythonString\/PyException\/exception(_:)","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"exception"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"url":"\/documentation\/_pythonstring\/pyexception\/exception(_:)","kind":"symbol","title":"PyException.exception(_:)","abstract":[],"role":"symbol"}}}